### ISSUE TITLE
Linker integration test run failed

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-service-s3#186]
After merging https://github.com/beyondstorage/go-service-s3/pull/175 into master, linker integration test run failed.
See https://github.com/beyondstorage/go-service-s3/runs/3357584184?check_suite_focus=true for more details.

**Comment by abyss-w** [comment]
Another possibility is that the format of the metadata returned by `HeadObject` has changed, just like qingstor, but there is no way to verify this.

**Comment by abyss-w** [comment]
> Another possibility is that the format of the metadata returned by `HeadObject` has changed, just like qingstor, but there is no way to verify this.

I ran into this problem today when implementing qingstor's CreateLink.

**Comment by JinnyYi** [comment]
> Another possibility is that the format of the metadata returned by `HeadObject` has changed, just like qingstor, but there is no way to verify this.

Yes. Seems not null pointer exception as there's no related error info.

**Comment by abyss-w** [comment]
https://github.com/minio/minio/issues/7451#issuecomment-479421680
The results from him show that the first letter of the returned metadata will be capitalized, as in qingstor.

**Comment by abyss-w** [comment]
I will fix this issue

**Comment by Xuanwo** [comment]
Builg log here: https://teamcity.beyondstorage.io/viewLog.html?buildId=5&buildTypeId=GoServiceS3_IntegrationTests&tab=buildLog&_focus=223

**Comment by Xuanwo** [comment]
Fixed in #185
